
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAIL = 'GOOGLE_LOGIN_FAIL';
export const SET_HIGHSCORE = 'SET_HIGHSCORE';

export const GAME_NUMBER_PRESSED_CORRECT = 'GAME_NUMBER_PRESSED_CORRECT';
export const GAME_NUMBER_PRESSED_WRONG = 'GAME_NUMBER_PRESSED_WRONG';
export const GAME_RESET = 'GAME_RESET';